// Normally generated by wasm-pack
export async function default() {
    console.log("WASM init placeholder");
}
export class Hangman {
    static new() {
        return {
            guess: (c) => true,
            current_state: () => "_ _ _ _",
            is_over: () => false,
            is_won: () => false,
        };
    }
}
